allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@types/node@26.6.0'
  - autoprefixer@10.6.1
  - '@astrojs/ts-plugin@1.10.12'
  - astro@7.3.3
  - prettier-plugin-astro@1.0.1
