name: Pull Request to Source

on:
  workflow_dispatch:
  pull_request:
    branches:
      - source

concurrency:
  group: pr-to-source-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7

      # https://github.com/pnpm/action-setup
      - uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript check
        run: pnpm tsc

      - name: Run lint check
        run: pnpm lint

      - name: Build
        run: pnpm build
